language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - sudo apt-get install nunit-console
script:
  - xbuild DarkCloud2Inventor.sln
  - nunit-console DarkCloud2InventorTest/bin/Debug/DarkCloud2InventorTest.dll