language: csharp
solution: DarkCloud2Inventor.sln
install:
  - nuget DarkCloud2Inventor.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug DarkCloud2Inventor.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DarkCloud2InventorTest/bin/Debug/DarkCloud2InventorTest.dll